// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZoS9lpaDKgLtnhEsLF2j2LOIE2fib5lg',
    appId: '1:326685713636:web:64a39f9e50210dbb82b8f1',
    messagingSenderId: '326685713636',
    projectId: 'semana-computacao',
    authDomain: 'semana-computacao.firebaseapp.com',
    storageBucket: 'semana-computacao.firebasestorage.app',
    measurementId: 'G-F7NBXPNGFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcLc5vHmU3BdnDqJzA0CNmU1xFgHyk0G4',
    appId: '1:326685713636:android:01bca3e15e7dc5dc82b8f1',
    messagingSenderId: '326685713636',
    projectId: 'semana-computacao',
    storageBucket: 'semana-computacao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoYB7HGydX6WJgrJG7SWUXn6-HhYqY5b4',
    appId: '1:326685713636:ios:455ac4d9077fec5382b8f1',
    messagingSenderId: '326685713636',
    projectId: 'semana-computacao',
    storageBucket: 'semana-computacao.firebasestorage.app',
    iosBundleId: 'com.example.secApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoYB7HGydX6WJgrJG7SWUXn6-HhYqY5b4',
    appId: '1:326685713636:ios:455ac4d9077fec5382b8f1',
    messagingSenderId: '326685713636',
    projectId: 'semana-computacao',
    storageBucket: 'semana-computacao.firebasestorage.app',
    iosBundleId: 'com.example.secApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZoS9lpaDKgLtnhEsLF2j2LOIE2fib5lg',
    appId: '1:326685713636:web:6acef09b795f0ec382b8f1',
    messagingSenderId: '326685713636',
    projectId: 'semana-computacao',
    authDomain: 'semana-computacao.firebaseapp.com',
    storageBucket: 'semana-computacao.firebasestorage.app',
    measurementId: 'G-76E8THLLHG',
  );
}
